### ISSUE TITLE
Icons not being displayed or formatted after upgrading to 2023.2.x

### ISSUE THREAD

**Issue by kaizersoje** [thomasloven/lovelace-template-entity-row#100] opened 2023-02-03 01:40 UTC
I have noticed that after upgrading to 2023.2.x icons are not being displayed or formatted as before.

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:weather-windy
    name: "Beaufort scale: {{ states('sensor.beaufort') }}"
    state: "{{ state_attr('sensor.beaufort','description') }}"
    card_mod:
      style: |
        :host {
        --paper-item-icon-color:
          {%- set beaufort = states('sensor.beaufort') | float -%}
          {%- if beaufort >= 9 -%} rgb(244, 67, 54)
          {%- elif beaufort >= 7 -%} #C68C71
          {%- elif beaufort >= 5 -%} #F2AA19
          {%- elif beaufort >= 3 -%} #E4C23D
          {%- elif beaufort >= 1 -%} #57C6EA
          {%- else -%} #5BC04D
          {%- endif -%}
          ;
        }
  - type: custom:template-entity-row
    icon: mdi:sun-thermometer-outline
    entity: sensor.heatindex
    name: "Heat Index: {{ states('sensor.heatindex') }}"
    state: "{{ state_attr('sensor.heatindex','description') }}"
    card_mod:
      style:
        template-entity-row$: |
          state-badge {
            color: 
              {%- set heatindex = states('sensor.heatindex') | float -%}
              {%- if heatindex >= 54 -%} rgb(244, 67, 54)
              {%- elif heatindex >= 41 -%} #C68C71
              {%- elif heatindex >= 32 -%} #F2AA19
              {%- elif heatindex >= 26 -%} #E4C23D
              {%- else -%} #5BC04D
              {%- endif -%}
              ;
            }
  - type: custom:template-entity-row
    name: Estimate
    icon: mdi:currency-usd
    state: |
      {{ 
        "${:.2f}".format(
            (states('sensor.daily_grid_consumption')|float(none) * states('input_number.grid_tariff')|float) + 
            states('input_number.power_daily_charge')|float/100 - 
            (states('sensor.pv_eday')|float(none) * states('input_number.solar_feedin_tariff')|float)
        ) 
      }}
    card_mod:
      style:
        state-badge$: |
          ha-state-icon{
            color:
              {%- set amt = (states('sensor.daily_grid_consumption')|float(none) * states('input_number.grid_tariff')|float) + 
                  states('input_number.power_daily_charge')|float/100 - 
                  (states('sensor.pv_eday')|float(none) * states('input_number.solar_feedin_tariff')|float) -%}
              {%- if amt > 0 -%} #CD5C5C
              {%- else -%} #3CB371
              {%- endif -%}
              !important;
          }
        .: |
          .state {
            font-weight: 500;
            font-size: 13pt;
            color:
              {%- set amt = (states('sensor.daily_grid_consumption')|float(none) * states('input_number.grid_tariff')|float) + 
                  states('input_number.power_daily_charge')|float/100 - 
                  (states('sensor.pv_eday')|float(none) * states('input_number.solar_feedin_tariff')|float) -%}
              {%- if amt > 0 -%} #CD5C5C
              {%- else -%} #3CB371
              {%- endif -%}
              !important;
          }
```

This is how it looks.

![image](https://user-images.githubusercontent.com/54566217/216490812-783f2bfa-675a-4285-8666-ed9a6b9d81b7.png)

**Comment by ildar170975** [comment] 2023-02-03 01:48
If you really want to find out a reason of your issue - try to at least localize it. Posting a code with a complex logic and things not related to the card does not help nether you nor other users who may help.

**Comment by kaizersoje** [comment] 2023-02-03 05:26
Well, here is just one entity that I have isolated from the entities above.

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:weather-windy
    name: 'Beaufort scale: {{ states(''sensor.beaufort'') }}'
    state: '{{ state_attr(''sensor.beaufort'',''description'') }}'
```

![image](https://user-images.githubusercontent.com/54566217/216519343-b2b8324a-d044-4ba5-aaa3-ec3f329dfc33.png)

**Comment by bdormael** [comment] 2023-02-03 07:01
I have the same issue wherever I use custom:template-entity-row and have the “icon: mid:…” mentioned
Same issue with custom:fold-entity-row

**Comment by sagaland93** [comment] 2023-02-03 07:49
Same here.

When I'm using 'custom:template-entity-row' the icon is not displayed.
Doesn't seem to matter if I set an icon or not - It's blank regardless.

**Comment by michalolborski** [comment] 2023-02-03 08:30
you can easily fix it by changing line 8 in template-entity-row.js
`.stateObj=${s}`
to this
`.stateObj=${this.hass.states[this.config.entity]}`

Im not sure why author did this weird parse json thingy inside. Generally if you don't specify entity in configuration then icon will disappear (despite if you specified it in icon prop)

Ps. remember to remove template-entity-row.js.gz after changing template-entity-row.js on your local setup, and refresh cache ;)

**Comment by sagaland93** [comment] 2023-02-03 08:35
@michalolborski ; Worked. Thank you!

**Comment by michalolborski** [comment] 2023-02-03 09:18
@thomasloven, could you kindly check this PR: https://github.com/thomasloven/lovelace-template-entity-row/pull/101, I believe I fixed this issue and also: 
https://github.com/thomasloven/lovelace-template-entity-row/issues/95 and https://github.com/thomasloven/lovelace-template-entity-row/issues/94

**Comment by ildar170975** [comment] 2023-02-08 23:40
Confirmed - an icon is NOT displayed if no entity is defined:
```
      type: custom:template-entity-row
      state: yyy
      name: xxx
      icon: mdi:car
```
![изображение](https://user-images.githubusercontent.com/71872483/217676660-e596ba7f-c23e-4439-afdf-7fbd969bee32.png)

**Comment by ildar170975** [comment] 2023-03-28 08:19
The issue seems to be resolved in the latest update.
Thank you , @thomasloven

**Comment by 50494554524F** [comment] 2023-04-19 17:43
bug still present: icon is not showed if no entity was specified

workaround: i'm using an entity_id and then i define custom text and icon

**Comment by ildar170975** [comment] 2024-02-11 23:45
May be closed imho

**Comment by thomasloven** [comment] 2024-02-12 08:22
Thanks!

**Closed by thomasloven** 2024-02-12 08:22 UTC
